language: go
go: 
 - 1.10.x

install:
 - go get -v
 - go get -v github.com/bitly/go-simplejson
 - go get -v github.com/fatih/color

script:
 - cp ./config_sample.json ./config.json
 - go test -v ./...
